# Generated by Django 4.2.7 on 2025-10-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_job_customer_confirmed_at_job_customer_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='work_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
