# Generated by Django 4.2.7 on 2025-11-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicecategory_is_active_and_more'),
        ('payments', '0002_providerwallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerwallet',
            options={'verbose_name': 'Provider Wallet', 'verbose_name_plural': 'Provider Wallets'},
        ),
        migrations.AlterField(
            model_name='providerwallet',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='services.serviceprovider'),
        ),
    ]
