# Generated by Django 4.2.7 on 2025-11-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicecategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
