# Generated by Django 4.2.7 on 2025-11-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceprovider_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service_categories',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory'),
            preserve_default=False,
        ),
    ]
