# Generated by Django 4.2.7 on 2025-11-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_serviceprovider_service_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service_category',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_categories',
            field=models.ManyToManyField(to='services.servicecategory'),
        ),
    ]
