# Generated by Django 4.2.7 on 2025-11-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='average_rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='business_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_categories',
            field=models.ManyToManyField(blank=True, related_name='providers', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='total_jobs_completed',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['name', 'is_active'], name='services_se_name_7a5db8_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['is_active', 'is_verified'], name='services_se_is_acti_203324_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['location', 'is_active'], name='services_se_locatio_056419_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['average_rating', 'is_active'], name='services_se_average_ae47c0_idx'),
        ),
    ]
