# Generated by Django 4.2.7 on 2025-11-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_job_servicecategory_serviceprovider_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
